name: autominify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          touch minify.css
          for module in $(find ../modules/ -name '*.css')
          do
            data=$(cat $module)
            data=${data//[$'\t\r\n']}
            echo $data >> minify.css
          done
      - name: Output minifyed css file
        uses: actions/upload-artifact@v2
        with:
          name: minifyed css
          path: minify.css

